camel:
  springboot:
    name: EFinanceiraContext
spring:
  main:
    sources: net.jlstechnology.Application
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:sped;DB_CLOSE_DELAY=-1
    name: null
    username: null
    password: null
  jpa:
    database-platform: net.jlstechnology.efinanceira.domain.util.FixedH2Dialect
    database: H2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: create-drop